services:
  app:
    container_name: sfu-app
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app/dist
      - ./cert:/app/cert
    network_mode: host  